import { buildCardDeck } from "../../engine/parsers/nec-input";
import { parseNecDocument } from "../../engine/parsers/nec-document";
import { editorModelFingerprint } from "../wire-editor/model-fingerprint";
import type { EditorModelTransfer } from "./types";

type TransferCore = Pick<EditorModelTransfer,
  "wires" | "excitations" | "loads" | "transmissionLines" | "ground" |
  "geometryGroundFlag" | "frequencyRange" | "frequencySegments"
>;

export function transferFingerprint(model: TransferCore): string {
  return editorModelFingerprint({
    wires: model.wires,
    excitations: model.excitations,
    loads: model.loads,
    transmissionLines: model.transmissionLines,
    ground: model.ground,
    geometryGroundFlag: model.geometryGroundFlag,
    frequencyRange: model.frequencyRange,
    frequencySegments: model.frequencySegments,
  });
}

export function assessTransferDeckParity(sourceNecDeck: string, model: TransferCore) {
  const source = parseNecDocument(sourceNecDeck);
  if (!source.nec_document?.structured_editable) {
    const errors = source.nec_document?.diagnostics.filter((item) => item.severity === "error").map((item) => item.message) ?? [];
    return { semanticMatch: false, sourceFingerprint: "", editorFingerprint: transferFingerprint(model), summary: errors.join(" ") || "The source deck is not structurally editable.", regeneratedCards: [] as string[] };
  }
  const sourceFingerprint = editorModelFingerprint({
    wires: source.wires,
    excitations: source.excitations.map((excitation) => {
      const wire = source.wires.find((candidate) => candidate.tag === excitation.wire_tag);
      return wire
        ? { ...excitation, position_ratio: (excitation.segment - 0.5) / wire.segments }
        : excitation;
    }),
    loads: source.loads ?? [],
    transmissionLines: source.transmission_lines ?? [],
    ground: source.ground ?? { type: "free_space" },
    geometryGroundFlag: source.geometry_ground_flag ?? null,
    frequencyRange: {
      start_mhz: source.frequency_start_mhz,
      stop_mhz: source.frequency_stop_mhz,
      steps: source.frequency_steps,
    },
    // A single FR block is the editor's ordinary frequencyRange. The
    // frequencySegments array is reserved for multiple explicit FR blocks.
    frequencySegments: (source.frequency_segments?.length ?? 0) > 1 ? source.frequency_segments : [],
  });
  const editorFingerprint = transferFingerprint(model);
  // Building the target deck here proves every field can pass through the
  // ordinary editor serializer. Output requests are intentionally regenerated.
  buildCardDeck({
    wires: model.wires,
    excitations: model.excitations,
    loads: model.loads,
    transmission_lines: model.transmissionLines,
    ground: model.ground,
    geometry_ground_flag: model.geometryGroundFlag,
    frequency: model.frequencyRange,
    frequencySegments: model.frequencySegments,
  });
  const semanticMatch = sourceFingerprint === editorFingerprint;
  return {
    semanticMatch,
    sourceFingerprint,
    editorFingerprint,
    summary: semanticMatch
      ? "Geometry, segmentation, source, ground and frequency are semantically identical. RP, PT and comments are regenerated by the editor."
      : "The source NEC model and proposed editor model differ in represented solver inputs.",
    regeneratedCards: ["CM", "CE", "PT", "RP", "EN"],
  };
}
