import { useMemo, useState } from "react";
import { Navbar } from "../components/layout/Navbar";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { HeightPolarPlot, type PolarSeries } from "../features/height-lab/HeightPolarPlot";
import { HeightRadiation3D } from "../features/height-lab/HeightRadiation3D";
import type { PatternDisplayMode } from "../features/height-lab/types";
import { adaptYagiToNec } from "../features/yagi-beams/nec-adapter";
import { generateYagiModel, hasYagiErrors, regenerateYagiStartingDimensions, resizeYagi, startingYagiModel, YAGI_BAND_PRESETS, yagiModelKey, yagiWavelengthM } from "../features/yagi-beams/model";
import type { SavedYagiTrace, YagiAntennaModel } from "../features/yagi-beams/schema";
import { useYagiCalculation } from "../features/yagi-beams/useYagiCalculation";
import { YagiCurrentPlot } from "../features/yagi-beams/YagiCurrentPlot";
import { YagiGeometry3D } from "../features/yagi-beams/YagiGeometry3D";
import { YagiSliderField } from "../features/yagi-beams/YagiSliderField";

const TRACE_COLORS = ["#a855f7", "#14b8a6", "#eab308", "#f43f5e"];

function signedReactance(value: number): string { return `${value < 0 ? "−" : "+"} j${Math.abs(value).toFixed(2)}`; }

function statusText(phase: string): string {
  if (phase === "debouncing") return "Geometry updated · waiting for a stable input…";
  if (phase === "calculating") return "Calculating this exact model in the local NEC worker…";
  if (phase === "cached") return "Result restored from the local in-memory model cache.";
  if (phase === "success") return "Calculation complete for the displayed geometry.";
  return "Resolve model errors before calculation.";
}

export function YagiBeamModelsPage() {
  const [model, setModel] = useState(() => startingYagiModel());
  const [mode, setMode] = useState<PatternDisplayMode>("absolute");
  const [traces, setTraces] = useState<SavedYagiTrace[]>([]);
  const generated = useMemo(() => generateYagiModel(model), [model]);
  const key = useMemo(() => yagiModelKey(model), [model]);
  const adapted = useMemo(() => { try { return adaptYagiToNec(generated); } catch { return null; } }, [generated]);
  const valid = !hasYagiErrors(generated) && adapted !== null;
  const calculation = useYagiCalculation(model, valid);
  const result = calculation.result;
  const lambda = yagiWavelengthM(model.frequencyHz);
  const errors = generated.issues.filter((issue) => issue.severity === "error");
  const warnings = [...generated.issues, ...(adapted?.issues ?? [])].filter((issue, index, all) => issue.severity === "warning" && all.findIndex((candidate) => candidate.code === issue.code) === index);
  const resultWarnings = (result?.warnings ?? []).filter((message) => !warnings.some((issue) => issue.message === message));
  const pending = calculation.phase === "debouncing" || calculation.phase === "calculating";
  const update = (change: Partial<YagiAntennaModel>) => setModel((current) => ({ ...current, ...change, provenance: { ...current.provenance, manualDimensions: true } }));
  const updateDirector = (index: number, change: { lengthM?: number; spacingFromPreviousM?: number }) => setModel((current) => ({ ...current, directors: current.directors.map((director, candidate) => candidate === index ? { ...director, ...change } : director), provenance: { ...current.provenance, manualDimensions: true } }));
  const updateGroundConductivity = (conductivitySPerM: number) => setModel((current) => current.ground.kind === "sommerfeld-norton" ? { ...current, ground: { ...current.ground, conductivitySPerM } } : current);
  const updateGroundPermittivity = (relativePermittivity: number) => setModel((current) => current.ground.kind === "sommerfeld-norton" ? { ...current, ground: { ...current.ground, relativePermittivity } } : current);
  const selectElements = (elements: number) => setModel((current) => {
    const next = startingYagiModel(current.frequencyHz, elements - 2);
    return { ...next, ground: current.ground, referenceImpedanceOhm: current.referenceImpedanceOhm, elementDiameterM: current.elementDiameterM };
  });
  const addTrace = () => {
    if (!result || traces.length >= 4) return;
    const id = `${Date.now()}-${traces.length}`;
    setTraces((current) => [...current, { id, label: `${model.directors.length + 2}-element · ${(model.boomHeightM / lambda).toFixed(2)}λ`, color: TRACE_COLORS[current.length]!, model: structuredClone(model), result }]);
  };
  const currentSeries: PolarSeries[] = result ? [{ id: "current", label: "Current model", color: "#f97316", points: result.azimuthPattern, pattern: result.radiationPattern, current: true }] : [];
  const azimuthSeries: PolarSeries[] = [...traces.map((trace) => ({ id: trace.id, label: trace.label, color: trace.color, points: trace.result.azimuthPattern, pattern: trace.result.radiationPattern })), ...currentSeries];
  const elevationSeries: PolarSeries[] = [...traces.map((trace) => ({ id: trace.id, label: trace.label, color: trace.color, points: trace.result.elevationPattern })), ...(result ? [{ id: "current", label: "Current model", color: "#f97316", points: result.elevationPattern, current: true }] : [])];

  return <div className="flex h-screen flex-col bg-background text-text-primary"><Navbar /><main className="min-h-0 flex-1 overflow-auto"><div className="mx-auto max-w-[1700px] p-4 lg:p-6">
    <header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-orange-500">Directional antenna laboratory</p><h1 className="mt-1 text-2xl font-bold">Parametric Yagi beam models</h1><p className="mt-1 max-w-4xl text-sm text-text-secondary">A dedicated typed model maps exact element dimensions to NEC-2. The gray boom is visual only; the conducting elements, source, ground, and displayed deck are the solved model.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" data-testid="yagi-reset" onClick={() => { setModel(startingYagiModel()); setTraces([]); }}>Reset</Button><Button size="sm" data-testid="yagi-save-comparison" onClick={addTrace} disabled={!result || traces.length >= 4}>Save comparison ({traces.length}/4)</Button></div></header>

    <div className="grid gap-5 xl:grid-cols-[390px_minmax(0,1fr)]"><aside className="space-y-4"><Card className="p-4"><h2 className="text-sm font-semibold">Array configuration</h2><div className="mt-3 grid grid-cols-3 gap-2">{[2, 3, 5].map((elements) => <button key={elements} type="button" data-testid={`yagi-preset-${elements}`} onClick={() => selectElements(elements)} className={`rounded border px-2 py-2 text-xs ${model.directors.length + 2 === elements ? "border-orange-500 bg-orange-500/10 text-orange-500" : "border-border"}`}>{elements}-element</button>)}</div><label className="mt-3 block text-xs font-medium" htmlFor="yagi-director-count">Configurable directors</label><div className="mt-1 flex items-center gap-2"><input id="yagi-director-count" data-testid="yagi-director-count" type="number" min="0" max="6" step="1" value={model.directors.length} onChange={(event) => setModel((current) => resizeYagi(current, Number(event.target.value)))} className="w-24 rounded border border-border bg-background px-2 py-1 text-right font-mono text-xs" /><input type="range" aria-label="Number of directors" data-testid="yagi-director-count-slider" min="0" max="6" step="1" value={model.directors.length} onChange={(event) => setModel((current) => resizeYagi(current, Number(event.target.value)))} className="min-w-0 flex-1 accent-orange-500" /></div><p className="mt-2 text-[10px] text-text-secondary">0 directors = 2-element; 1 = 3-element; 2–6 = configurable multi-element.</p></Card>

      <Card className="space-y-4 p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Frequency and starting dimensions</h2><span data-testid="yagi-dimension-mode" className="text-[10px] text-text-secondary">{model.provenance.manualDimensions ? "Manual dimensions" : "Starting dimensions"}</span></div><div><label htmlFor="yagi-frequency" className="text-xs font-medium">Frequency</label><div className="mt-1 flex items-center gap-1"><input id="yagi-frequency" data-testid="yagi-frequency" type="number" min="1.8" max="54" step="0.001" value={Number((model.frequencyHz / 1e6).toFixed(6))} onChange={(event) => update({ frequencyHz: Number(event.target.value) * 1e6 })} className="w-full rounded border border-border bg-background px-2 py-1 text-right font-mono text-xs" /><span className="text-[10px] text-text-secondary">MHz</span></div><p className="mt-1 text-[10px] text-text-secondary">Wavelength {lambda.toFixed(3)} m</p></div><div className="flex flex-wrap gap-1">{YAGI_BAND_PRESETS.map((band) => <button key={band.id} type="button" data-testid={`yagi-band-${band.id}`} onClick={() => setModel((current) => regenerateYagiStartingDimensions(current, band.frequencyHz))} className="rounded border border-border px-2 py-1 text-[10px] hover:border-orange-500">{band.label}</button>)}</div><Button variant="secondary" size="sm" className="w-full" onClick={() => setModel((current) => regenerateYagiStartingDimensions(current, current.frequencyHz))}>Regenerate frequency-based starting dimensions</Button><p className="text-[10px] leading-relaxed text-amber-600 dark:text-amber-300">These dimensions are starting points only. Textbook fractions do not guarantee resonance, match, gain, or front-to-back performance.</p></Card>

      <Card className="space-y-4 p-4"><h2 className="text-sm font-semibold">Element dimensions</h2><YagiSliderField label="Driven-element length" description={`${(model.drivenElementLengthM / lambda).toFixed(3)}λ`} value={model.drivenElementLengthM} min={0.5} max={100} step={0.01} unit="m" testId="yagi-driven-length" onChange={(value) => update({ drivenElementLengthM: value })} /><YagiSliderField label="Reflector length" description={`${(model.reflectorLengthM / lambda).toFixed(3)}λ`} value={model.reflectorLengthM} min={0.5} max={100} step={0.01} unit="m" testId="yagi-reflector-length" onChange={(value) => update({ reflectorLengthM: value })} /><YagiSliderField label="Reflector spacing" description="Behind driven element" value={model.reflectorSpacingM} min={0.1} max={30} step={0.01} unit="m" testId="yagi-reflector-spacing" onChange={(value) => update({ reflectorSpacingM: value })} />{model.directors.map((director, index) => <div key={director.id} className="space-y-3 rounded border border-border p-3"><p className="text-xs font-semibold text-cyan-500">Director {index + 1}</p><YagiSliderField label="Length" description={`${(director.lengthM / lambda).toFixed(3)}λ`} value={director.lengthM} min={0.5} max={100} step={0.01} unit="m" testId={`yagi-director-${index + 1}-length`} onChange={(value) => updateDirector(index, { lengthM: value })} /><YagiSliderField label="Spacing" description={index === 0 ? "From driven" : `From director ${index}`} value={director.spacingFromPreviousM} min={0.1} max={30} step={0.01} unit="m" testId={`yagi-director-${index + 1}-spacing`} onChange={(value) => updateDirector(index, { spacingFromPreviousM: value })} /></div>)}</Card>

      <Card className="space-y-4 p-4"><h2 className="text-sm font-semibold">Installation and ground</h2><YagiSliderField label="Boom height" description={`${(model.boomHeightM / lambda).toFixed(3)}λ above ground`} value={model.boomHeightM} min={0.2} max={80} step={0.05} unit="m" testId="yagi-height" onChange={(value) => update({ boomHeightM: value })} /><YagiSliderField label="Element diameter" description="Uniform thin-wire/tube equivalent" value={model.elementDiameterM * 1000} min={0.5} max={100} step={0.1} unit="mm" testId="yagi-diameter" onChange={(value) => update({ elementDiameterM: value / 1000 })} /><label className="block text-xs font-medium" htmlFor="yagi-ground">Ground model</label><select id="yagi-ground" data-testid="yagi-ground" value={model.ground.kind} onChange={(event) => update({ ground: event.target.value === "perfect" ? { kind: "perfect" } : { kind: "sommerfeld-norton", conductivitySPerM: 0.005, relativePermittivity: 13 } })} className="w-full rounded border border-border bg-background px-2 py-2 text-xs"><option value="perfect">Infinite perfect ground</option><option value="sommerfeld-norton">Sommerfeld/Norton real ground</option></select>{model.ground.kind === "sommerfeld-norton" && <div className="grid grid-cols-2 gap-2"><label className="text-[10px] text-text-secondary">Conductivity S/m<input data-testid="yagi-conductivity" type="number" min="0.00001" max="10" step="0.001" value={model.ground.conductivitySPerM} onChange={(event) => updateGroundConductivity(Number(event.target.value))} className="mt-1 w-full rounded border border-border bg-background px-2 py-1 text-right font-mono text-xs" /></label><label className="text-[10px] text-text-secondary">Relative permittivity<input data-testid="yagi-permittivity" type="number" min="1" max="100" step="1" value={model.ground.relativePermittivity} onChange={(event) => updateGroundPermittivity(Number(event.target.value))} className="mt-1 w-full rounded border border-border bg-background px-2 py-1 text-right font-mono text-xs" /></label></div>}<label className="block text-xs">SWR reference <select data-testid="yagi-reference-impedance" value={model.referenceImpedanceOhm} onChange={(event) => update({ referenceImpedanceOhm: Number(event.target.value) as 50 | 75 })} className="ml-2 rounded border border-border bg-background px-2 py-1"><option value="50">50 Ω</option><option value="75">75 Ω</option></select></label></Card>
    </aside>

    <div className="min-w-0 space-y-5"><section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><Card className="overflow-hidden p-3"><div className="flex items-center justify-between px-1 pb-2"><h2 className="text-sm font-semibold">Interactive array geometry</h2><span className="text-[10px] text-text-secondary">updates immediately</span></div><YagiGeometry3D wires={generated.wires} modelKey={key} /></Card><Card className="p-4"><h2 className="text-sm font-semibold">NEC model identity</h2><dl className="mt-3 space-y-2 text-xs"><div className="flex justify-between"><dt className="text-text-secondary">Elements</dt><dd data-testid="yagi-element-count" className="font-mono">{generated.wires.length}</dd></div><div className="flex justify-between"><dt className="text-text-secondary">Segments</dt><dd data-testid="yagi-segment-count" className="font-mono">{adapted?.segmentation.totalSegments ?? "—"}</dd></div><div className="flex justify-between"><dt className="text-text-secondary">Feed</dt><dd className="font-mono">tag {adapted?.segmentation.feed.tag ?? "—"} / centre</dd></div><div className="flex justify-between"><dt className="text-text-secondary">Forward axis</dt><dd className="font-mono">+Y / φ=90°</dd></div><div className="flex justify-between"><dt className="text-text-secondary">Ground</dt><dd className="font-mono">{model.ground.kind === "perfect" ? "GN 1" : "GN 2 (S/N)"}</dd></div><div className="flex justify-between"><dt className="text-text-secondary">Pattern grid</dt><dd className="font-mono">2° · 8,280 pts</dd></div></dl><p className="mt-4 text-[10px] leading-relaxed text-text-secondary">Odd segmentation targets ≤0.02λ per element. The source is always on the exact centre segment of the driven element.</p></Card></section>

      {errors.length > 0 && <div role="alert" data-testid="yagi-errors" className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm text-red-600">{errors.map((issue) => <p key={issue.code}>• {issue.message}</p>)}</div>}{(warnings.length > 0 || resultWarnings.length > 0) && <div data-testid="yagi-warnings" className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-xs text-amber-700 dark:text-amber-300">{warnings.map((issue) => <p key={issue.code}>• {issue.message}</p>)}{resultWarnings.map((message) => <p key={message}>• {message}</p>)}</div>}{calculation.error && <div role="alert" data-testid="yagi-solver-error" className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm text-red-600">{calculation.error}</div>}

      <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Debounced local NEC calculation</h2><p data-testid="yagi-calculation-status" className="mt-1 text-xs text-text-secondary">{statusText(calculation.phase)} · cache {calculation.cacheEntries}/48</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-semibold uppercase ${pending ? "bg-amber-500/15 text-amber-600" : result ? "bg-emerald-500/15 text-emerald-600" : "bg-surface-hover text-text-secondary"}`}>{calculation.phase}</span></div>{result && <section data-testid="yagi-results" className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-8">{[["Feed impedance", `${result.resistanceOhm.toFixed(2)} ${signedReactance(result.reactanceOhm)} Ω`, "yagi-result-impedance"], [`SWR (${model.referenceImpedanceOhm} Ω)`, result.swr >= 999 ? ">999" : result.swr.toFixed(2), "yagi-result-swr"], ["Forward gain", `${result.forwardGainDbi.toFixed(2)} dBi`, "yagi-result-forward-gain"], ["Axial rear gain", `${result.rearGainDbi.toFixed(2)} dBi`, "yagi-result-rear-gain"], ["Front-to-back", `${result.frontToBackDb.toFixed(2)} dB`, "yagi-result-fb"], ["Front-to-rear", `${result.frontToRearDb.toFixed(2)} dB`, "yagi-result-fr"], ["Az. beamwidth", result.beamwidthDeg === null ? "not resolved" : `${result.beamwidthDeg.toFixed(1)}°`, "yagi-result-beamwidth"], ["Take-off angle", `${result.takeOffAngleDeg.toFixed(1)}°`, "yagi-result-takeoff"]].map(([label, value, testId]) => <div key={label} className="rounded border border-border bg-background/50 p-3"><p className="text-[10px] text-text-secondary">{label}</p><p data-testid={testId} className="mt-1 font-mono text-sm font-semibold">{value}</p></div>)}</section>}<p className="mt-3 text-[10px] leading-relaxed text-text-secondary">Front-to-back compares the forward peak with the exact 180° axial sample at the same elevation. Front-to-rear compares it with the strongest radiation anywhere in the rear hemisphere. These are deliberately not treated as interchangeable.</p></Card>

      <Card className="p-4" data-testid="yagi-comparison-panel"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold">Comparison traces</h2><p className="text-[10px] text-text-secondary">Save up to four immutable solved models; dashed traces remain labelled while the orange current result changes.</p></div>{traces.length > 0 && <Button variant="ghost" size="sm" onClick={() => setTraces([])}>Clear</Button>}</div>{traces.length === 0 ? <p className="mt-3 text-xs text-text-secondary">No saved comparisons.</p> : <div className="mt-3 overflow-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-text-secondary"><tr><th>Model</th><th>Gain</th><th>F/B</th><th>F/R</th><th>Beamwidth</th><th>Impedance</th><th></th></tr></thead><tbody>{traces.map((trace) => <tr key={trace.id} className="border-t border-border"><td className="py-2" style={{ color: trace.color }}>{trace.label}</td><td>{trace.result.forwardGainDbi.toFixed(2)} dBi</td><td>{trace.result.frontToBackDb.toFixed(2)} dB</td><td>{trace.result.frontToRearDb.toFixed(2)} dB</td><td>{trace.result.beamwidthDeg?.toFixed(1) ?? "—"}°</td><td>{trace.result.resistanceOhm.toFixed(1)} {signedReactance(trace.result.reactanceOhm)} Ω</td><td><button type="button" aria-label={`Remove ${trace.label}`} onClick={() => setTraces((current) => current.filter((candidate) => candidate.id !== trace.id))} className="text-red-500">Remove</button></td></tr>)}</tbody></table></div>}</Card>

      <div className="flex justify-end"><button type="button" data-testid="yagi-pattern-mode" onClick={() => setMode((value) => value === "absolute" ? "normalised" : "absolute")} className="rounded border border-border bg-surface px-3 py-2 text-xs">{mode === "absolute" ? "Absolute dBi" : "Relative to peak"}</button></div><section className="grid gap-4 lg:grid-cols-2"><Card className="p-2"><HeightPolarPlot plane="azimuth" mode={mode} series={azimuthSeries} /></Card><Card className="p-2"><HeightPolarPlot plane="elevation" mode={mode} series={elevationSeries} /></Card></section><section className="grid gap-4 xl:grid-cols-2"><Card className="overflow-hidden p-3"><h2 className="px-1 pb-3 text-sm font-semibold">Interactive 3D radiation pattern</h2><HeightRadiation3D pattern={result?.radiationPattern ?? null} mode={mode} pending={pending} /></Card>{result ? <YagiCurrentPlot points={result.currentDistribution} /> : <Card className="grid min-h-80 place-items-center p-5 text-center text-sm text-text-secondary">Element-current magnitude and phase appear only for the current solved model.</Card>}</section>

      <details className="rounded-lg border border-border bg-surface p-4"><summary className="cursor-pointer text-sm font-semibold">Generated NEC model</summary><pre data-testid="yagi-generated-nec" className="mt-3 max-h-96 overflow-auto rounded bg-[#0b1020] p-4 text-xs leading-5 text-emerald-300">{adapted?.deck ?? "Resolve validity errors to generate NEC."}</pre></details>
      <Card className="p-4 text-xs leading-relaxed text-text-secondary"><h2 className="mb-2 text-sm font-semibold text-text-primary">Model scope and validity</h2><p>This workbench models straight, parallel, uniformly cylindrical elements with a delta-gap source and no conducting boom, mast, balun, feed line, element taper, mounting hardware, or material loss. Perfect and Sommerfeld/Norton grounds are distinct NEC models. Inspect warnings and perform convergence plus independent package comparisons before relying on a physical design. No optimiser is implemented.</p></Card>
    </div></div>
  </div></main></div>;
}
