import { Grid, Line, OrbitControls } from "@react-three/drei";
import { useMemo } from "react";
import { SafeCanvas } from "../../components/three/SafeCanvas";
import type { GeneratedLoopBeamModel, LoopBeamPoint3M } from "./schema";

function Scene({ generated }: { generated: GeneratedLoopBeamModel }) {
  const bounds = useMemo(() => { const points = generated.wires.flatMap((wire) => [wire.startM, wire.endM]); const spanX = Math.max(...points.map((p) => p.x)) - Math.min(...points.map((p) => p.x)); const spanY = Math.max(...points.map((p) => p.y)) - Math.min(...points.map((p) => p.y)); const spanZ = Math.max(...points.map((p) => p.z)); const centre = { x: (Math.max(...points.map((p) => p.x)) + Math.min(...points.map((p) => p.x))) / 2, y: (Math.max(...points.map((p) => p.y)) + Math.min(...points.map((p) => p.y))) / 2 }; return { centre, scale: 6 / Math.max(spanX, spanY, spanZ, 0.1) }; }, [generated]);
  const map = (point: LoopBeamPoint3M): [number, number, number] => [(point.x - bounds.centre.x) * bounds.scale, point.z * bounds.scale, (point.y - bounds.centre.y) * bounds.scale]; const colour = (family: string) => family === "reflector" ? "#a855f7" : family === "director" ? "#22d3ee" : "#fb923c"; const feed = generated.wires.find((wire) => wire.source)!; const feedMid = map({ x: (feed.startM.x + feed.endM.x) / 2, y: (feed.startM.y + feed.endM.y) / 2, z: (feed.startM.z + feed.endM.z) / 2 });
  return <><ambientLight intensity={1.25} /><directionalLight position={[4, 8, 5]} intensity={2} /><Grid args={[14, 14]} cellColor="#334155" sectionColor="#0f766e" fadeDistance={14} />{generated.supports.map((support) => <Line key={support.id} points={[map(support.startM), map(support.endM)]} color="#64748b" lineWidth={1.5} dashed dashSize={0.12} gapSize={0.08} />)}{generated.wires.map((wire) => <Line key={wire.id} points={[map(wire.startM), map(wire.endM)]} color={colour(wire.family)} lineWidth={wire.source ? 6 : 3} />)}<mesh position={feedMid}><sphereGeometry args={[0.11, 18, 18]} /><meshStandardMaterial color="#60a5fa" emissive="#1d4ed8" emissiveIntensity={0.6} /></mesh>{generated.intendedForwardAxis && <Line points={[[0, 0.15, 0], [0, 0.15, 2.1]]} color="#facc15" lineWidth={4} />}<OrbitControls makeDefault enablePan={false} minDistance={3} maxDistance={15} /></>;
}
export function LoopBeamGeometry3D({ generated, modelKey }: { generated: GeneratedLoopBeamModel; modelKey: string }) { return <div className="relative h-96 overflow-hidden rounded-md bg-[#07111f]" data-testid="loop-beam-geometry-3d" data-model-key={modelKey} data-wire-count={generated.wires.length}><span className="sr-only">Interactive solved-wire geometry. Orange is driven conductor, purple is reflector, cyan is director, blue marks the feed segment, and gray lines are non-conducting supports.</span><SafeCanvas camera={{ position: [7, 5.5, 8], fov: 43 }} dpr={[1, 1.5]}><Scene generated={generated} /></SafeCanvas><div className="pointer-events-none absolute bottom-2 left-2 rounded bg-black/60 px-2 py-1 text-[10px] text-slate-200">driven: orange · reflector: purple · director: cyan · feed: blue · supports: dashed gray</div></div>; }
